name: Auto-add issues and PRs to Roadmap project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  contents: read
  projects: write
  issues: read
  pull-requests: read

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/ChincoLinux/projects/3
          github-token: ${{ secrets.PROJECT_PAT }}
